language: python
python:
  - 3.5
  - 3.6-dev
  - nightly

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-asyncio
  - pip install pytest-pep8

script:
  - py.test --pep8
  - python3.5 setup.py test
